services:
  backend_telegram_bot_itilium:
    image: ckala62rus/backend_telegram_bot_itilium:latest
    container_name: backend_telegram_bot_itilium
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    command: bash -c "python app.py"
    ports:
      - "8001:8001"
    volumes:
      - ./src:/src
      - ./.env:/src/.env

  redis_itilium:
    image: "redis:6.2.7"
    container_name: redis_itilium
    ports:
      - "6379:6379"
    restart: no
    environment:
      - TZ=Europe/Moscow
