services:
  itilium_telegram_bot_prod:
    image: ckala62rus/backend_telegram_bot_itilium_prod:latest
    container_name: itilium_telegram_bot_back
    build:
      context: .
      dockerfile: ./docker/backend_prod/Dockerfile
    command: bash -c "python app.py"
    volumes:
      - ./docker/prod/.env:/src/.env
    depends_on:
      - redis_itilium_telegram_bot_prod

  redis_itilium_telegram_bot_prod:
    image: "redis:6.2.7"
    container_name: redis_itilium_telegram_bot_prod
    command: bash -c "redis-server --requirepass $$REDIS_PASSWORD"
    env_file:
      - docker.env
    ports:
      - "6379:6379"
    restart: no
    environment:
      - TZ=Europe/Moscow
