name: Build and Publish Docker Images Itilium Bot

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Publish to Registry ( ckala62rus/backend_telegram_bot_itilium:latest )
        uses: docker/build-push-action@v4
        with:
          file: ./docker/backend/Dockerfile
          push: true
          tags: ckala62rus/backend_telegram_bot_itilium:latest
